services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  scraper:
    build: .
    container_name: product_scraper
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env
    command: python src/scraping/scraper.py

volumes:
  postgres_data:
