CREATE TABLE  materials (
    id SERIAL PRIMARY KEY,
    description VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO materials (description) VALUES
('babador de plástico'),
('agulha curta/longa'),
('anestésico tópico'),
('anestésico injetável (ARTICAÍNA) (50 tubetes)'),
('broca diamantada esférica HL'),
('broca 3080/3082'),
('roletes de algodão'),
('gaze'),
('dique de borracha'),
('top dam (isolamento)'),
('paramonoclorofenol'),
('clorexidina gel 2%'),
('hipoclorito 2.5%'),
('agulha irrigação MK LIFE'),
('seringa descartável'),
('kit de limas K manuais'),
('kit limas 8 ou 10 (apenas um uso)'),
('sistema rotatório (FLAT FILE)'),
('sistema rotatório (SEQUENCE)'),
('sistema rotatório (PRO-T)'),
('sistema rotatório (PRO-R)'),
('sistema rotatório (RECIPROC)'),
('solução EDTA'),
('Eucaliptol (retratamento)'),
('cones de papel (esterilizado - 5un)'),
('medicação intracanal (ULTRACAL)'),
('cimento obturador (SEALER PLUS)'),
('cones de guta percha (TAPPER 04 ou 06)'),
('cones de guta percha (CONE M e FM)'),
('envelope de esterilização (grande)'),
('envelope de esterelizaçao (pequeno)'),
('selador provisório (Villevie)'),
('ionômero de vidro');